name: CI Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r ../requirements.txt
      - name: Run Tests
        run: pytest tests/ --tb=short -v

  frontend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend-livros
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run Build/Lint
        run: npm run build # Ou npm test se tiver configurado
